replicaCount: 1

image:
  repository: olexandrod/simple-flask  
  tag: "latest"
  pullSecrets:
    - name: regcred

service:
  type: NodePort
  port: 80
  nodePort: 30090

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi