name: Deploy Infrastructure

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_bucket_name: "simple-site-20253004"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        id: configure
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::050451395507:role/github-oidc-role
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Check if S3 bucket exists
        id: check_s3
        run: |
          if aws s3api head-bucket --bucket $TF_VAR_bucket_name 2>/dev/null; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Dump bucket check
        run: |
          echo "Bucket exists: ${{ steps.check_s3.outputs.exists }}"

      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: terraform
        env:
          TF_LOG: DEBUG
          TF_LOG_PATH: terraform-init.log

      - name: Import existing S3 bucket into state
        if: ${{ steps.check_s3.outputs.exists == 'true' }}
        run: |
          terraform import module.s3.aws_s3_bucket.static_site $TF_VAR_bucket_name
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform
        env:
          TF_LOG: DEBUG
          TF_LOG_PATH: terraform-valid.log
      
      - name: Terraform Refresh
        run: terraform refresh # Додано крок refresh
        working-directory: terraform
        env:
          TF_LOG: DEBUG
          TF_LOG_PATH: terraform-refresh.log

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform
        env:
          TF_LOG: DEBUG
          TF_LOG_PATH: terraform-plan.log

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          TF_LOG: DEBUG
          TF_LOG_PATH: terraform-apply.log

      - name: Upload index.html to S3
        run: |
          aws s3 cp ./site/index.html s3://${TF_VAR_bucket_name}/index.html
          aws s3 cp ./site/nike.mp4 s3://${TF_VAR_bucket_name}/nike.mp4 \
          --content-type "video/mp4" \
          --metadata-directive REPLACE

      - name: Показати CloudFront Domain Name
        run: terraform output cloudfront_domain_name
        working-directory: terraform    

      - name: Show Terraform logs
        if: always()
        run: |
          echo "::group::Terraform Init Log"
          cat terraform/terraform-init.log || echo "No init log found"
          echo "::endgroup::"
  
          echo "::group::Terraform Validate Log"
          cat terraform/terraform-valid.log || echo "No validate log found"
          echo "::endgroup::"
         
          echo "::group::Terraform Refresh Log" # Додано вивід логів для refresh
          cat terraform/terraform-refresh.log || echo "No refresh log found"
          echo "::endgroup::"

          echo "::group::Terraform Plan Log"
          cat terraform/terraform-plan.log || echo "No plan log found"
          echo "::endgroup::"
  
          echo "::group::Terraform Apply Log"
          cat terraform/terraform-apply.log || echo "No apply log found"
          echo "::endgroup::"
