name: Destroy EC2 ASG nodes

on:
  workflow_dispatch:

jobs:
  destroy-ec2:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::050451395507:role/github-oidc-role
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy ASG Master
        run: terraform destroy -auto-approve -target=modules.k8s.k8s_kontrolplane

      - name: Terraform Destroy ASG Worker
        run: terraform destroy -auto-approve -target=modules.k8s.k8s_node
