name: Destroy K8S Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::050451395507:role/github-oidc-role
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/environments/dev

      - name: Destroy ASG Master
        run: terraform destroy -auto-approve -target=module.ec2.module.asg_master.aws_autoscaling_group.this[0]
        working-directory: terraform/environments/dev

      - name: Destroy ASG Worker
        run: terraform destroy -auto-approve -target=module.ec2.module.asg_worker.aws_autoscaling_group.this[0]
        working-directory: terraform/environments/dev

      - name: Destroy EC2 Module
        run: terraform destroy -auto-approve -target=module.ec2
        working-directory: terraform/environments/dev

      - name: Destroy K8S Module
        run: terraform destroy -auto-approve -target=module.k8s
        working-directory: terraform/environments/dev

      - name: Final Destroy (everything else)
        run: terraform destroy -auto-approve
        working-directory: terraform/environments/dev
